### PR TITLE
[MCC-229209] Upgrade the PM to support Rails 5.2

### PR DESCRIPTION
**Pull request by hstebbins-mdsol**
This PR upgrades the Policy Machine to Rails 5.2.

### CODE REVIEW

**Comment by DMcKinnon-mdsol** [comment]
Is it still going to be backwards compatible with Rails 4?

**Comment by hstebbins-mdsol** [comment]
I doubt it, primarily due to the change in how JSONB serialization is handled, but I'll give it a shot and update here.

**Comment by hstebbins-mdsol** [comment]
Thankfully, I was wrong! It appears to still be compatible.

**Comment by DMcKinnon-mdsol** [comment]
Merging in 2hrs unless objections @mdsol/team-04.

**Pull request merged**
