### PR TITLE
Develop into Master in preparation for tagging

### PR DESCRIPTION
**Pull request by CGDS**
title says it all.  @DMcKinnon-mdsol, @PoloPro, @HonoreDB

### CODE REVIEW

**Comment by DMcKinnon-mdsol** [comment]
Specs?

**Comment by DMcKinnon-mdsol** [comment]
Oh develop into master. Eh...specs anyways because I'm paranoid? Do we need to update some version somewhere?

**Comment by DMcKinnon-mdsol** [comment]
...well...good to see we kept up with https://github.com/mdsol/the_policy_machine/blob/develop/lib/policy_machine/version.rb

**Comment by CGDS** [comment]
version bump and specs
```
Finished in 45.94 seconds
765 examples, 0 failures, 12 pending
```

**Pull request merged**
