### PR TITLE
rename parents to immediate_ancestors

### PR DESCRIPTION
**Pull request by drozenberg**
rename parents method which is overloaded in Dalton

### CODE REVIEW

**Comment by drozenberg** [comment]
@mdsol/team-04

**Comment by HonoreDB** [comment]
Not to complicate your life, but isn't the Dalton `parents` semantically the same thing? Couldn't you do a quick migration to assign prts to their parents (if they're not already) and then use the existing method?

Also, it's weird that these are conflicting since they're supposed to be at different encapsulation levels.

**Comment by DMcKinnon-mdsol** [comment]
My local policy machine is also in a bad state, so I cannot currently run this test suite for you, but can you open a PR to dalton off of this PM branch so that we can see Dalton's tests passing? That'd be good enough for me to merge.

**Comment by DMcKinnon-mdsol** [comment]
All specs pass locally for me on this branch:
```
Finished in 58.2 seconds
769 examples, 0 failures, 12 pending
```

I'm regressing this branch with dalton tests here: https://github.com/mdsol/dalton/pull/1706.

I'll merge this PR once the build on 1706 on dalton passes.

**Comment by DMcKinnon-mdsol** [comment]
@drozenberg Dalton didn't like the changes out of the box, which isn't unexpected. Mind also taking over https://github.com/mdsol/dalton/pull/1706 ?

**Comment by DMcKinnon-mdsol** [comment]
The build for the linked PR to dalton off this branch passed, so I'll merge this in 1hr unless objections @HonoreDB @CGDS @PoloPro.

**Comment by DMcKinnon-mdsol** [comment]
....or not

**Comment by DMcKinnon-mdsol** [comment]
@drozenberg Aaron's comment has sufficiently confused me. Why do we need this?

**Comment by DMcKinnon-mdsol** [comment]
nvm x 2. Connor walked me through what's going on now. May fix not in the pm, though. holding off on merging.

**Pull request closed without merging**
