### PR TITLE
Admit that we're preloading objects into memory and just fetch their ids instead

### PR DESCRIPTION
**Pull request by HonoreDB**
Specs pass, seems like it shaves about a second off of the long tail we're trying to fix.

### CODE REVIEW

**Comment by DMcKinnon-mdsol** [comment]
👍

**Comment by HonoreDB** [comment]
Got rid of the pointless `|` between heterogeneously typed arrays.

**Comment by CGDS** [comment]
cool, looks good @HonoreDB.  Assume specs still pass?

**Comment by HonoreDB** [comment]
Specs still pass.

**Comment by DMcKinnon-mdsol** [comment]
👍

**Pull request merged**
