### PR TITLE
Coalesced Privileges Test Branch

### PR DESCRIPTION
**Pull request by hstebbins-mdsol**
This PR is a test branch for changes to the core privilege derivation in the ActiveRecord adapter

### CODE REVIEW

**Comment by hstebbins-mdsol** [comment]
@DMcKinnon-mdsol should I close this? I totally forgot about it.

**Comment by hstebbins-mdsol** [comment]
It worked in November. I'm not sure if it still works as-is, but I don't see why it wouldn't, I guess.

**Comment by DMcKinnon-mdsol** [comment]
This decreased the time of privilege shows by around 80%, right? 

Can you provide more details about its performance?

TBD on whether this is worth merging since it's VERY high-impact core logic and would require a ton of regression testing.

**Comment by hstebbins-mdsol** [comment]
> This decreased the time of privilege shows by around 80%, right?

i vaguely remember it was from ~30ms -> ~10ms

> Can you provide more details about its performance?

sure, but i'll need some time to figure that out. an ETA for that depends on priority, i guess, and i'm assuming this is fairly low priority.

**Comment by DMcKinnon-mdsol** [comment]
Yea, alas it is currently low-priority.

**Comment by DMcKinnon-mdsol** [comment]
@hstebbins-mdsol might this PR still be potentially relevant?

**Comment by hstebbins-mdsol** [comment]
I think it's probably so low priority it's worth just closing. 😢

**Pull request closed without merging**
